name: Notion->Publish
on:
  schedule:
    - cron: "0 18 * * *"
  push:
    branches:
      - master
  workflow_dispatch:  # This enables manual triggering

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm i
      - name: Pull Docs from Notion
        env:
          DOCU_NOTION_INTEGRATION_TOKEN: ${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}
          DOCU_NOTION_DOCS_PAGE: ${{ secrets.DOCU_NOTION_DOCS_PAGE }}
        run: npm run pulldocs
      - name: Pull Blog from Notion
        env:
          DOCU_NOTION_INTEGRATION_TOKEN: ${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}
          DOCU_NOTION_BLOG_PAGE: ${{ secrets.DOCU_NOTION_BLOG_PAGE }}
          DOCU_NOTION_BLOG_PATH: ${{ secrets.DOCU_NOTION_BLOG_PATH}}
        run: npm run pullblog
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_SAND_037D23D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "/build"
